language: node_js
node_js:
  - "10.11.0"
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
